# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                default_target_path: field-of-study_index
#                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: %requires_channel% }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: %requires_channel% }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: %requires_channel% }
        - { path: ^/subjects/ajax, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: %requires_channel% }
        - { path: ^/admin/, role: ROLE_ADMIN, requires_channel: %requires_channel% }