# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    AppBundle\EventSubscriber\LocaleSubscriber:
        arguments: ['%kernel.default_locale%']
        # redundant if you're using autoconfigure
        tags: [kernel.event_subscriber]

    AppBundle\Service\USOSService:
        arguments:
            - "%consumer_key%"
            - "%consumer_secret%"
            - "%usos_api_base_url%"
            - "%self_url%"
            - '@router'
